apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets-jesusramirez
  namespace: backend-namespace-jesusramirez
type: Opaque
data:
  DATABASE_USER: bXl1c2Vy  # `echo -n 'myuser' | base64`
  DATABASE_PASSWORD: bXlwYXNzd29yZA==  # `echo -n 'mypassword' | base64`
  AWS_ACCESS_KEY_ID: YWNjZXNzX2tleQ==  # `echo -n 'access_key' | base64`
  AWS_SECRET_ACCESS_KEY: c2VjcmV0X2tleQ==  # `echo -n 'secret_key' | base64`
