apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-jesusramirez
  namespace: backend-namespace-jesusramirez
data:
  DATABASE_HOST: "mysql-db"
  DATABASE_PORT: "3306"
  APP_ENV: "production"
  LOG_LEVEL: "info"
