apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup-jesusramirez
  namespace: backend-namespace-jesusramirez
spec:
  schedule: "0 */3 * * *"  # Cada 3 horas
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-jesusramirez
              image: amazon/aws-cli
              command:
                - /bin/sh
                - -c
                - |
                  TIMESTAMP=$(date +"%Y%m%d%H%M%S")
                  BACKUP_DIR="/backup"
                  BUCKET_NAME="bucket-codigo-backup"
                  DB_NAME="mydatabase"
                  DB_USER=$(echo $DATABASE_USER | base64 --decode)
                  DB_PASS=$(echo $DATABASE_PASSWORD | base64 --decode)

                  mkdir -p $BACKUP_DIR
                  mysqldump -h mysql-db -u $DB_USER -p$DB_PASS $DB_NAME > $BACKUP_DIR/db_backup_$TIMESTAMP.sql
                  
                  aws s3 cp $BACKUP_DIR/db_backup_$TIMESTAMP.sql s3://$BUCKET_NAME/jesusramirez/database/$TIMESTAMP/

              envFrom:
                - secretRef:
                    name: backend-secrets-jesusramirez
          restartPolicy: OnFailure
