name: Deploy to Kubernetes

on:
  push:
    branches:
      - develop  # Esto se ejecutará cuando haya un push en la rama develop

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # 1. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t jesusramirezgamarra/backend-dynamic-db:latest .
          docker push jesusramirezgamarra/backend-dynamic-db:latest

  deploy-k8:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      # 1. Set up Kubernetes (use base64 encoded kubeconfig)
      - name: Set up Kubernetes using kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.CLUSTER_KUBE_CONFIG_K8 }}" | base64 -d > $HOME/.kube/config
        env:
          CLUSTER_KUBE_CONFIG_K8: ${{ secrets.CLUSTER_KUBE_CONFIG_K8 }}

      # 2. Deploy to Kubernetes
      - name: Deploy to Kubernetes (Minikube or DigitalOcean)
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/cronjob-backup.yaml

      # 3. Verify deployment
      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get svc
